from tkinter import *
# Hearts
photo1h = PhotoImage(file='')
photo2h = PhotoImage(file='')
photo3h = PhotoImage(file='')
photo4h = PhotoImage(file='')
photo5h = PhotoImage(file='')
photo6h = PhotoImage(file='')
photo7h = PhotoImage(file='assets\samplecard.png')
photo8h = PhotoImage(file='')
photo9h = PhotoImage(file='')
photo10h = PhotoImage(file='')
photo11h = PhotoImage(file='')
photo12h = PhotoImage(file='')
photo13h = PhotoImage(file='')
# Diamonds
photo1d = PhotoImage(file='')
photo2d = PhotoImage(file='')
photo3d = PhotoImage(file='')
photo4d = PhotoImage(file='')
photo5d = PhotoImage(file='')
photo6d = PhotoImage(file='')
photo7d = PhotoImage(file='')
photo8d = PhotoImage(file='')
photo9d = PhotoImage(file='')
photo10d = PhotoImage(file='')
photo11d = PhotoImage(file='')
photo12d = PhotoImage(file='')
photo13d = PhotoImage(file='')
# Spades
photo1s = PhotoImage(file='')
photo2s = PhotoImage(file='')
photo3s = PhotoImage(file='')
photo4s = PhotoImage(file='')
photo5s = PhotoImage(file='')
photo6s = PhotoImage(file='')
photo7s = PhotoImage(file='')
photo8s = PhotoImage(file='')
photo9s = PhotoImage(file='')
photo10s = PhotoImage(file='')
photo11s = PhotoImage(file='')
photo12s = PhotoImage(file='')
photo13s = PhotoImage(file='')
# Clubs
photo1c = PhotoImage(file='')
photo2c = PhotoImage(file='')
photo3c = PhotoImage(file='')
photo4c = PhotoImage(file='')
photo5c = PhotoImage(file='')
photo6c = PhotoImage(file='')
photo7c = PhotoImage(file='')
photo8c = PhotoImage(file='')
photo9c = PhotoImage(file='')
photo10c = PhotoImage(file='')
photo11c = PhotoImage(file='')
photo12c = PhotoImage(file='')
photo13c = PhotoImage(file='')
